<?php

/**
 * @file
 * Implements hooks for sending mail on webform submission.
 */

use Drupal\webform\WebformSubmissionInterface;
use Drupal\Core\Render\Markup;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_webform_submission_insert().
 *
 * This hook gets webform submitted data and node url.
 * Uses the mailManager service to send the mail to user and admin.
 */
function send_mail_webform_submission_insert(WebformSubmissionInterface $webform_submission) {
  // Storing the webform id being stored.
  $webform_id = $webform_submission->getWebform()->id();
  // Condition that runs only on submission of event registration form.
  if ($webform_id === 'registration') {
    $values = $webform_submission->getData();
    $email = $values['email'] ?? NULL;
    // $name = $values['name']['first'] ?? '';
    $full_name = $values['full_name'] ?? NULL;
    // $password = $values['password'] ?? '';
    $role = $values['role'] ?? '';

    // It prepares the message and looks at the implementation of mail hook.
    $mailManager = \Drupal::service('plugin.manager.mail');
    $module = 'send_mail';
    $key = 'webform_submission';
    $langcode = \Drupal::currentUser()->getPreferredLangcode();

    // Mail of admin.
    $admin_mail = \Drupal::config('system.site')->get('mail');
    $params_admin['subject'] = 'Registration Form Submission';
    $params_admin['message'] = Markup::create("New registration received from <b>{$full_name}</b> Email: {$email} \n Role: {$role}");
    $mailManager->mail($module, $key, $admin_mail, $langcode, $params_admin);

    // Mail of user.
    if ($email) {
      $params_user['subject'] = 'Thank You';
      $params_user['message'] = Markup::create("Hello {$full_name},<br><br>Thankyou for your registration. We will get back to you soon.");
      $mailManager->mail($module, $key, $email, $langcode, $params_user);
    }
  }
}

/**
 * Implements hook_mail().
 *
 * This hook actually prepares the email message to be sent.
 */
function send_mail_mail($key, &$message, $params) {
  switch ($key) {
    case 'webform_submission':
      $message['subject'] = $params['subject'];
      $message['body'][] = $params['message'];
      break;
  }
}
